### ISSUE TITLE
Error parse replay

### ISSUE THREAD

**Issue by kpachbiu88** [skadistats/smoke#3] opened 2014-03-31 13:33 UTC
Traceback (most recent call last):
  File "parser.py", line 156, in <module>
    for match in demo.play():
  File "ticker.pyx", line 18, in **iter** (smoke/replay/ticker.c:1878)
  File "plexer.pyx", line 60, in smoke.io.plexer.Plexer.read_tick (smoke/io/plexer.c:1607)
AssertionError: 23

What is it ?

**Comment by onethirtyfive** [comment] 2014-03-31 18:55
This isn't reproducible. Please provide match ID or something more than that stack trace.

Many things could cause this, not all of which the fault of the library.

Closing until I can reproduce.

**Comment by kpachbiu88** [comment] 2014-04-01 05:19
Link on 588578682.dem file:
https://disk.yandex.ru/public/?hash=yIuaFXrcxoI0UA869k5nmg0AcYkvIXKaO9ga13urE8w%3D

**Comment by onethirtyfive** [comment] 2014-04-25 08:59
Hi @kpachbiu88,

One assert was causing the parse to fail. Your replay is unique--the assert is wrong. Since this can happen to other people, I've disabled the assertion.

Pull changes and try again!

**Closed as completed by onethirtyfive** 2014-04-25 08:59 UTC
